### ISSUE TITLE
【提问】关于 API Key 泄露的问题

### ISSUE THREAD

**Issue by Young-Lord** [bojieyang/indexnow-action#71]
根据官方的[最佳实践](https://www.bing.com/indexnow#bestPractices:~:text=Sending%20a%20lot%20of%20URLs%20doesn%E2%80%99t%20affect%20ranking%20but%20continuous%20sending%20might)，不建议连续多次提交，否则可能影响网站排名
但只要 repo 是公开的，你的 key 就算用了 secret 也显然不能防止攻击者把你的站点批量提交直到超出提交限额

**Comment by Young-Lord** [comment]
个人认为我这个方案更好，key 只在部署时写入
https://github.com/Young-Lord/Young-Lord.github.io/commit/44c0dc6b278427d2657f73d803c7b14756d37535

**Comment by bojieyang** [comment]
连续多次提交的问题，可以考虑通过组合配置action的schedule和since参数来限制，比如schedule设置为每天执行一次，同时sicne设置为1 day。这样只有最近一天新增或变化的URL会被提交。

关于公开repo可以被找到api key file位置导致可能遭到恶意攻击批量提交到超出限额的问题，我之前确实忽略了这种情况。你的方案很好，我在下次更新时会加上相关的部署说明来避免这种情况。

**Comment by bojieyang** [comment]
@Young-Lord  我已经更新了readme文档，增加了在部署时生成IndexNow key文件一节，以避免在公共仓库的泄露问题。感谢你提供的方案。
